import React from 'react'
import { ArrowDownTrayIcon, ClipboardDocumentCheckIcon, TrashIcon } from '@heroicons/react/24/outline'

function NotesDisplay({ notes, transcript, onExport, onClear }) {
  const handleCopy = () => {
    navigator.clipboard.writeText(notes.formatted)
      .then(() => alert('Notes copied to clipboard!'))
      .catch(err => console.error('Failed to copy keys', err))
  }

  return (
    <div className="w-full max-w-4xl mx-auto space-y-8 animate-slide-up pb-12">
      {/* Actions Bar */}
      <div className="flex flex-col sm:flex-row justify-between items-center gap-4 bg-white dark:bg-dark-card p-4 rounded-xl border border-gray-200 dark:border-dark-border shadow-sm">
        <h2 className="text-xl font-display font-bold text-gray-900 dark:text-white flex items-center gap-2">
          <span className="w-2 h-8 bg-primary-500 rounded-full"></span>
          Generated Notes
        </h2>
        <div className="flex flex-wrap gap-2">
          <button
            onClick={handleCopy}
            className="btn-secondary flex items-center gap-2 text-sm px-4 py-2"
          >
            <ClipboardDocumentCheckIcon className="w-4 h-4" />
            Copy Text
          </button>
          <div className="flex gap-1 bg-gray-100 dark:bg-slate-700 p-1 rounded-lg">
            <button
              onClick={() => onExport('pdf')}
              className="px-3 py-1.5 text-sm font-medium text-gray-600 dark:text-gray-300 hover:bg-white dark:hover:bg-slate-600 hover:shadow-sm rounded-md transition-all"
            >
              PDF
            </button>
            <button
              onClick={() => onExport('txt')}
              className="px-3 py-1.5 text-sm font-medium text-gray-600 dark:text-gray-300 hover:bg-white dark:hover:bg-slate-600 hover:shadow-sm rounded-md transition-all"
            >
              TXT
            </button>
          </div>
          <button
            onClick={onClear}
            className="p-2 text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg transition-colors"
            title="Clear Results"
          >
            <TrashIcon className="w-5 h-5" />
          </button>
        </div>
      </div>

      {/* Main Content */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        {/* Navigation / TOC */}
        <div className="md:col-span-1 space-y-6">
          <div className="card p-6 sticky top-24">
            <h3 className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-4">Contents</h3>
            <nav className="space-y-2">
              {['Introduction', 'Key Points', 'Examples', 'Conclusion'].map((item) => (
                <a
                  key={item}
                  href={`#${item.toLowerCase().replace(' ', '-')}`}
                  className="block text-gray-600 dark:text-gray-400 hover:text-primary-600 dark:hover:text-primary-400 hover:translate-x-1 transition-all duration-200"
                >
                  {item}
                </a>
              ))}
            </nav>

            <div className="mt-8 pt-6 border-t border-gray-100 dark:border-slate-700">
              <h3 className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-2">Metadata</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Generated by AutoNotes AI <br />
                {new Date().toLocaleDateString()}
              </p>
            </div>
          </div>
        </div>

        {/* Content Area */}
        <div className="md:col-span-2 space-y-6">
          {/* Summary Card */}
          <div id="introduction" className="card p-6 md:p-8">
            <h3 className="text-2xl font-display font-bold text-gray-900 dark:text-white mb-4">Introduction</h3>
            <div className="prose dark:prose-invert max-w-none text-gray-600 dark:text-gray-300 leading-relaxed">
              {notes.structured?.introduction || "No introduction available."}
            </div>
          </div>

          {/* Key Points */}
          <div id="key-points" className="card p-6 md:p-8 border-l-4 border-l-primary-500">
            <h3 className="text-xl font-display font-bold text-gray-900 dark:text-white mb-6 flex items-center gap-2">
              Key Takeaways
            </h3>
            <ul className="space-y-4">
              {notes.structured?.key_points?.map((point, index) => (
                <li key={index} className="flex gap-4 items-start group">
                  <span className="flex-shrink-0 w-6 h-6 rounded-full bg-primary-100 dark:bg-primary-900/40 text-primary-600 dark:text-primary-400 flex items-center justify-center text-sm font-bold mt-0.5 group-hover:scale-110 transition-transform">
                    {index + 1}
                  </span>
                  <span className="text-gray-700 dark:text-gray-300">{point}</span>
                </li>
              )) || <p className="text-gray-500">No key points extracted.</p>}
            </ul>
          </div>

          {/* Other Sections */}
          <div id="examples" className="card p-6 md:p-8">
            <h3 className="text-xl font-display font-bold text-gray-900 dark:text-white mb-4">Examples & Details</h3>
            <ul className="list-disc pl-5 space-y-2 text-gray-600 dark:text-gray-300">
              {notes.structured?.examples?.map((ex, i) => (
                <li key={i}>{ex}</li>
              )) || <p>No specific examples found.</p>}
            </ul>
          </div>

          <div id="conclusion" className="card p-6 md:p-8 bg-gradient-to-br from-indigo-50 to-white dark:from-slate-800 dark:to-slate-900">
            <h3 className="text-xl font-display font-bold text-gray-900 dark:text-white mb-3">Conclusion</h3>
            <p className="text-gray-700 dark:text-gray-300 italic">
              {notes.structured?.conclusion || "No conclusion available."}
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default NotesDisplay
